import { createApi, fetchBaseQuery } from "@reduxjs/toolkit/query/react";
import { Api } from "./Api";

// Define your base API service:
export const authApi = createApi({
  reducerPath: "authApi", // unique key for this API slice
  baseQuery: fetchBaseQuery({ baseUrl: Api }), // your API base URL here
  tagTypes: ["User"], // used for cache invalidation if needed
  endpoints: (build) => ({
    login: build.mutation({
      query: ({ formData }) => ({
        url: "auth/login",
        method: "POST",
        body: formData,
      }),
    }),
    register: build.mutation({
      query: (formData) => ({
        url: "auth/register",
        method: "POST",
        body: formData,
      }),
    }),
    logout: build.mutation({
      query: () => ({
        url: "auth/logout",
        method: "POST",
      }),
    }),
    // Add more endpoints for other actions following the same pattern
  }),
});

// Export hooks auto-generated by RTK Query
export const { useLoginMutation, useRegisterMutation, useLogoutMutation } =
  authApi;
