import { createApi, fetchBaseQuery } from "@reduxjs/toolkit/query/react";
import { Api } from "./Api";

// Define your base API service:
export const userApi = createApi({
  reducerPath: "userApi", // unique key for this API slice
  baseQuery: fetchBaseQuery({
    baseUrl: Api,
    prepareHeaders: (headers) => {
      const token = localStorage.getItem("access_token");
      if (token) {
        headers.set("Authorization", `Bearer ${token}`);
      }
      return headers;
    },
  }), // your API base URL here
  tagTypes: ["User"], // used for cache invalidation if needed
  endpoints: (build) => ({
    getUser: build.query({
      query: () => "/user",
      providesTags: ["User"],
    }),
    getAnotherUserProfile: build.query({
      query: (user_id) => `/profile/${user_id}`,
      providesTags: ["User"],
    }),
    getSuggestedUsersToFollow: build.query({
      query: ({ offset, limit }) =>
        `/user/suggested?offset=${offset}&limit=${limit}`,
      providesTags: ["User"],
    }),
    updateUserImage: build.mutation({
      query: (formData) => ({
        url: "/user/image",
        method: "POST",
        body: formData,
      }),
      invalidatesTags: ["User"],
    }),
    updateUserInformation: build.mutation({
      query: (formData) => ({
        url: "/user/update",
        method: "PUT",
        body: formData,
      }),
      invalidatesTags: ["User"],
    }),
  }),
});

// Export hooks auto-generated by RTK Query
export const {
  useGetAnotherUserProfileQuery,
  useGetSuggestedUsersToFollowQuery,
  useGetUserQuery,
  useUpdateUserInformationMutation,
  useUpdateUserImageMutation,
} = userApi;
